# Generated by Django 4.2.19 on 2025-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked Out", "Checked Out"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
